### ISSUE TITLE
Definition of LCOM metric used-please specify and rules to detect implementation smells

### ISSUE THREAD

**Issue by sac111** [tushartushar/DesigniteJava#70]
I am sorry to say I could not find which definition of LCOM is being used here . I would request to please specify how LCOM here is calculated.

Also I am not able to find rules to detect various implementation smells - can you please specify...

Thanks.

**Comment by Thodoras** [comment]
An informal Definition of LCOM that we use is the following: we divide the
properties of a class into connected components. Connected components
contain properties of the class that are method-connected. Two properties
are method connected iff if there exists a method that accesses these two
methods or it calls other methods that at some point access these two
methods or a combination of the above.

Finally we compute lcom like this:
If all properties live in a single connected component then lcom is 0
otherwise is calculated: number of connected components with more than one
elements / number of methods in the class.


This I hope answers to your first question....

**Comment by sac111** [comment]
Thanks for reply..
According to definition... low value of LCOM is preferable...
I am right??....

**Comment by Thodoras** [comment]
Yes, 0 is totally cohesive. Worst case scenario is that you'll have each
property corresponding to one method then the ratio above will be equal to
1.
So yes the lower the lcom value is the most cohesive your class will be...

**Comment by sac111** [comment]
Right sir..
**I guess that the informal definition of LCOM used here is quite close to TCC which is calculated as** 
NP = N * (N-1) / 2 where N is the number of methods
NDC = number of direct connections (number of edges in the connection graph)
Tight class cohesion (TCC) = NDC/NP

So what is your comment on it...

**Also please clarify on the 2nd question given below...**

I am not able to find rules to detect various implementation smells - can you please specify...

**Comment by tushartushar** [comment]
Regarding your first question, please take a look at this [post](http://www.tusharma.in/technical/revisiting-lcom/). It might give you more clarity.

The rules to detect various implementation smells are only documented within the source code. You may explore the source code and let us know if something specific needs more clarification. Even better, you may contribute back to the project by creating the same :)

**Comment by sac111** [comment]
okay...

I got your point...

**Comment by mehrotrasan16** [comment]
I have used DesigniteJava to analyze an open source project(PDFsam) for a class project, and some of the LCOM values are -1. Could you please explain how this is calculated?
[typeMetrics.xlsx](https://github.com/tushartushar/DesigniteJava/files/4385005/typeMetrics.xlsx)

**Comment by tushartushar** [comment]
@mehrotrasan16 The discussion on this issue elaborates the rationale. Please go through it. Also look at this [post](http://www.tusharma.in/technical/revisiting-lcom/).
